spring:
  application:
    name: image-upload-service
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

logging:
  level:
    com.gardrops: DEBUG
    org.springframework.web: DEBUG

app:
  max-images-per-session: 10