spring:
  application:
    name: image-upload-service
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

logging:
  level:
    com.gardrops: DEBUG
    org.springframework.web: DEBUG

app:
  max-images-per-session: 10